version: "3"

services:
    anki-container:
        image: fruitjeus/anki-sync-server:${ANKI_VERSION}
        environment:
          - SYNC_USER1=${SYNC_USER1}
        ports:
          - ${PORT}:8080
        volumes:
          - /data/anki/data:/anki_data
