version: "3"

services:
    anki-container:
        image: fruitjeus/anki-sync-server:${ANKI_VERSION}
        container_name: anki-container
        restart: always
        environment:
          - SYNC_USER1=${SYNC_USER1}
        ports:
          - ${PORT}:${PORT}
        volumes:
          - /data/anki/data:/app/data
