version: "3"

services:
    anki-container:
        image: fruitjeus/anki-sync-server:${ANKI_VERSION}
        container_name: anki-container
        restart: always
        ports:
        - ${PORT}:${PORT}
        volumes:
        - /data/anki/data:/app/data
