version: "3"

services:
    anki-container:
        image: kuklinistvan/anki-sync-server:latest
        container_name: anki-container
        restart: always
        ports:
        - "27701:27701"
        volumes:
        - /data/anki/data:/app/data
