version: "3"
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=82
      - PGID=82
      - TZ=${TZ}
      - PASSWORD=${PASSWORD}
      - CLI_ARGS= #optional
    volumes:
      - /data/nextcloud/data/data/admin/files/Personal/Library:/config
    ports:
      - 8084:8080
      - 8085:8081
      - 9090:9090
