version: "3"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /data/calibre/config:/config
      - /data/calibre/library:/books
    ports:
      - 8083:8083
