version: "3"
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - PASSWORD=${PASSWORD}
      - CLI_ARGS= #optional
    volumes:
      - /data/nextcloud/data/data/admin/files/Personal/Library:/config
    ports:
      - 8084:8080
      - 8085:8081
