version: '3'
services:
  esphome:
    container_name: esphome
    image: esphome/esphome
    volumes:
      - /data/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    restart: always
    privileged: true
    ports:
      - "6052:6052"
