version: '3'
services:
  snipe-it:
    image: lscr.io/linuxserver/snipe-it:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
      - APP_URL=https://snipeit.wghomeserver.duckdns.org
      - MYSQL_PORT_3306_TCP_ADDR=${MYSQL_HOST}
      - MYSQL_PORT_3306_TCP_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - APP_ENV=production #optional
      - APP_DEBUG=false #optional
      - APP_LOCALE=en-US #optional
    volumes:
      - /data/snipeit:/config
    ports:
      - 2222:80
  
  mariadb:
    image: mariadb:10.6.4-focal
    volumes:
    - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_DATABASE=${MYSQL_DB}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_PREFIX=null
      - DB_DUMP_PATH='/usr/bin'
      - DB_CHARSET=utf8mb4
      - DB_COLLATION=utf8mb4_unicode_ci

    ports:
      - "3306:3306"

volumes:
  db: {}
