version: "3"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
      - SERVERURL=${SERVER_URL}
      - SERVERPORT=${SERVER_PORT}
      - PEERS=1 #optional
      - PEERDNS=auto #optional
    volumes:
      - /data/wireguard-server/config:/config
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    deploy:
      labels:
        io.portainerhack.cap_add: NET_ADMIN,SYS_MODULE
